[homologation]
homolog-01 ansible_host=IP_DO_HOST ansible_user=USUARIO_DO_ANSIBLE

[production]
prod-01 ansible_host=IP_DO_HOST ansible_user=USUARIO_DO_ANSIBLE

[test]
test-01 ansible_host=IP_DO_HOST ansible_user=USUARIO_DO_ANSIBLE