<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyModel" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Primitives" Version="9.0.0" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WarehouseManagementService.Application\WarehouseManagementService.Application.csproj" />
    <ProjectReference Include="..\WarehouseManagementService.Domain\WarehouseManagementService.Domain.csproj" />
    <ProjectReference Include="..\WarehouseManagementService.Infra.Data\WarehouseManagementService.Infra.Data.csproj" />
  </ItemGroup>

</Project>
